### ISSUE TITLE
Test strategy for poolable objects

### ISSUE THREAD

**Issue by lsolano** [yanggujun/commonsfornet#1]
## Are you planning to port or implement the following ?

Hi @yanggujun 

I need the ability to test my objects before giving the instances to clients (Acquire), and / or after returning them to the pool (Return), also I need to be able to invalidate an object given by the pool if it becomes unusable, but detected by the client code. Also, a nice to have, will be the test-on-create functionality.

Basically these three features are the `testOnBorrow`, `testOnReturn`, and `invalidateObject` from the original framework. See:

- [BaseGenericObjectPool.getTestOnBorrow()](https://commons.apache.org/proper/commons-pool/api-2.4.2/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getTestOnBorrow--)
- [BaseGenericObjectPool.getTestOnReturn](https://commons.apache.org/proper/commons-pool/api-2.4.2/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getTestOnReturn--)
- [ObjectPool.invalidateObject(T obj)](https://commons.apache.org/proper/commons-pool/api-2.4.2/org/apache/commons/pool2/ObjectPool.html#invalidateObject-T-)
- [BaseGenericObjectPool.getTestOnCreate()](https://commons.apache.org/proper/commons-pool/api-2.4.2/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#getTestOnCreate--)

My proposal will be to have a helper class to do the Tests (the current Factory or a new Tester/Validator one), this helper class should hold all related configuration properties and the required operations. At the Pool level we'll have only the Invalidate Object operation, this will be called within the same pool after validation or from the outside.  Something like the following:

### Pool Level Operations
`	void Invalidate(T obj);`

### Helper Level Operations
`IPooledObjectTester `
```
	(property) TestOnAcquire : bool
	(property) TestOnReturn : bool
	Test(T obj) : bool
```

or `IPooledObjectValidator`
```
	(property) ValiateOnAcquire : bool
	(property) ValidateOnReturn : bool
	Validate(T obj) : bool
```

Of course if you need some extra hands with that I can start working on a fork.

Regards,

**Comment by yanggujun** [comment]
No, it is not in the original plan. 
The design of the commons.pool is different from the apache one. 

But if there is a need I will look into this (may have different impl). And any PR is welcome.

**Comment by lsolano** [comment]
@yanggujun 

> But if there is a need I will look into this (may have different impl).

I do have that need I need to detect broken connection (non DB/RDBMS) to external resources and to have a way to leave those out the pool.


Here you have my proposal  => #2

Basically I went with the `IPooledObjectValidator` option, and the associated operation and changes to 

- `IObjectPool<T>` and `GenericObjectPool<T>`
- `IPoolDescriptor<T>` and `GenericPoolDescriptor<T>`: please note that `GenericPoolDescriptor<T>` has a fix on the implementation regarding null destroyer function and what the interface was dictating. Lines 111 (new) or 96 (old).

The changes to `PoolManager` were typos and a IDE warning (making `genericPools` and `keyedPools` readonly).

The files with more (a lot) of additions is the test file `ObjectPoolTest`, I wanted to create a separate file, but ended working on the same one to keep things together.

**Comment by lsolano** [comment]
Merged into master.
