### ISSUE TITLE
Commons.Pool depends on System.Data.Common?

### ISSUE THREAD

**Issue by AgentFire** [yanggujun/commonsfornet#3]
Not sure why the "lightweight" pool solution depends on a database-oriented package.
Can't find any code in the https://github.com/yanggujun/commonsfornet/tree/master/src/Commons.Pool which would use those DB types.

**Comment by yanggujun** [comment]
I think it's because the DefaultDbConnectionFactory class.

**Comment by AgentFire** [comment]
Whatever, then. Just doesn't seem right.

**Comment by yanggujun** [comment]
probably remove the DefaultDbConnectionFactory and make it as a sample, not included in the package
