### ISSUE TITLE
Upload release version 0.3.0.775 of Commons.Pool with object validation to NuGet

### ISSUE THREAD

**Issue by rubms** [yanggujun/commonsfornet#5]
I am interested in using the pooled object validation from Commons.Pool, inluded in version 0.3.0.755.
Could the version 0.3.0.775 of Commons.Pool be uploaded to NuGet?

**Comment by yanggujun** [comment]
Yes, will release a new version in Oct. Sorry for the late response, too busy with my current work.

**Comment by yanggujun** [comment]
The latest version which includes the object validation in Commons.Pool is released. Closing the issue.
