### ISSUE TITLE
Support [Flags] Enum Deserialization

### ISSUE THREAD

**Issue by dustinlacewell** [yanggujun/commonsfornet#6]
Currently, serializing an enum marked with [Flags] attribute works. You get a comma-separated list of enum-value names. However, deserializing does not work and result in a Dictionary key-not-found error.

I might recommend serializing enums to integer values instead of string-based names.

**Comment by yanggujun** [comment]
I see. missing the flag enums. I will check this.

**Comment by yanggujun** [comment]
Attribute.IsDefined is not supported in net standard 1.3.
I am trying to add a new build dependency on net standard 2.1. This is still on preview. After net standard 2.1 is released, I will fix this issue. And will try to adopt Span<T> for json (de)serialization.
